apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: multicluster-controlplane-pvc-volume
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.pvc.storageCapacity }}
  {{- if .Values.pvc.storageClassName }}
  storageClassName: {{ .Values.pvc.storageClassName }}
  {{- end }}
  {{- if .Values.pvc.selector }}
  selector:: {{ .Values.pvc.selector }}
  {{- end }}
