# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multicluster-controlplane
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: multicluster-controlplane
subjects:
- kind: ServiceAccount
  name: multicluster-controlplane-sa
  namespace: {{ .Release.Namespace }}
