{{ $caCrt := "" }}
{{ $caKey := "" }}

{{- if .Values.apiserver.ca }}
{{ $caCrt = .Values.apiserver.ca }}
{{ $caKey = (required "apiserver.cakey should be set together with apiserver.ca" .Values.apiserver.cakey) }}
{{- end }}

{{- if .Values.apiserver.generateCA }}
{{ $ca := genCA "ca" 3650 }}
{{ $caCrt = $ca.Cert }}
{{ $caKey = $ca.Key }}
{{- end }}

{{- $proxyCA := genCA "proxy-ca" 3650 }}
{{- $proxyClient := genSignedCert "front-proxy-client" nil nil 3650 $proxyCA }}

apiVersion: v1
kind: Secret
metadata:
  name: controlplane-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ocmconfig.yaml: |-
    apiserver:
      externalHostname: {{ .Values.apiserver.externalHostname }}
      port: {{ .Values.apiserver.externalPort }}
      {{- if $caCrt }}
      caFile: "/controlplane_config/apiserver_ca.crt"
      caKeyFile: "/controlplane_config/apiserver_ca.key"
      {{- end }}
    etcd:
      mode: {{ .Values.etcd.mode }}
      prefix: {{ .Release.Namespace }}
      {{- if (eq .Values.etcd.mode "external") }}
        {{- if (not .Values.etcd.servers) }}
          {{- fail "etcd.servers should be set together with etcd.mode" }}
        {{- end }}
      servers:
      {{- range .Values.etcd.servers }}
      - {{ . }}
      {{- end }}
      caFile: "/controlplane_config/etcd_ca.crt"
      certFile: "/controlplane_config/etcd_cert.crt"
      keyFile: "/controlplane_config/etcd_cert.key"
      {{- end }}
    aggregator:
      proxyClientCertFile: /controlplane_config/proxy-client.crt
      proxyClientKeyFile: /controlplane_config/proxy-client.key
      requestheaderClientCAFile: /controlplane_config/requestheader-client-ca.crt
      requestheaderUsernameHeaders: ["X-Remote-User"]
      requestheaderGroupHeaders: ["X-Remote-Group"]
      requestheaderExtraHeadersPrefix: ["X-Remote-Extra-"]
      requestheaderAllowedNames: ["front-proxy-client"]

  {{- if $caCrt }}
  apiserver_ca.crt: {{ $caCrt | quote  }}
  apiserver_ca.key: {{ $caKey | quote  }}
  {{- end }}

  requestheader-client-ca.crt: {{ $proxyCA.Cert | quote }}
  requestheader-client-ca.key: {{ $proxyCA.Key | quote }}
  proxy-client.crt: {{ $proxyClient.Cert | quote }}
  proxy-client.key: {{ $proxyClient.Key | quote }}

  {{- if (eq .Values.etcd.mode "external") }}
  etcd_ca.crt: {{ (required "etcd.ca should be set together with etcd.mode" .Values.etcd.ca) | quote }}
  etcd_cert.crt: {{ (required "etcd.cert should be set together with etcd.mode" .Values.etcd.cert) | quote }}
  etcd_cert.key: {{ (required "etcd.certkey should be set together with etcd.mode" .Values.etcd.certkey) | quote }}
  {{- end }}
