apiVersion: v1
kind: Secret
metadata:
  name: controlplane-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ocmconfig.yaml: |-
    apiserver:
      externalHostname: {{ .Values.apiserver.externalHostname }}
      port: 443
      {{- if and .Values.apiserver.caFile .Values.apiserver.caKeyFile }}
      caFile: "/controlplane_config/{{ .Values.apiserver.caFile | base }}"
      caKeyFile: "/controlplane_config/{{ .Values.apiserver.caKeyFile | base }}"
      {{- end }}
    etcd:
      mode: {{ .Values.etcd.mode }}
      prefix: {{ .Release.Namespace }}
      {{- if and (eq .Values.etcd.mode "external") (and .Values.etcd.caFile (and .Values.etcd.certFile (and .Values.etcd.keyFile (not (empty .Values.etcd.servers))))) }}
      servers:
      {{- range $index, $value := .Values.etcd.servers }}
      - {{ $value }}
      {{- end }}
      caFile: "/controlplane_config/{{ .Values.etcd.caFile }}"
      certFile: "/controlplane_config/{{ .Values.etcd.certFile }}"
      keyFile: "/controlplane_config/{{ .Values.etcd.keyFile }}"
      {{- end }}

data:
{{- if and .Values.apiserver.caFile .Values.apiserver.caKeyFile }}
{{ (.Files.Glob .Values.apiserver.caFile).AsSecrets | indent 2  }}
{{ (.Files.Glob .Values.apiserver.caKeyFile).AsSecrets | indent 2 }}
{{- end }}
{{- if and (eq .Values.etcd.mode "external") ( and (and .Values.etcd.caFile (and .Values.etcd.certFile .Values.etcd.keyFile)) (not (empty .Values.etcd.servers)) ) }}
{{ (.Files.Glob .Values.etcd.caFile).AsSecrets | indent 2 }} 
{{ (.Files.Glob .Values.etcd.certFile).AsSecrets | indent 2 }}
{{ (.Files.Glob .Values.etcd.keyFile).AsSecrets | indent 2 }}
{{- end}}
