apiVersion: v1
kind: Secret
metadata:
  name: controlplane-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ocmconfig.yaml: |-
    apiserver:
      externalHostname: {{ .Values.apiserver.externalHostname }}
      port: 443
      {{- if (and .Values.apiserver.ca .Values.apiserver.cakey) }}
      caFile: "/controlplane_config/apiserver_ca.crt"
      caKeyFile: "/controlplane_config/apiserver_ca.key"
      {{- end }}
    etcd:
      mode: {{ .Values.etcd.mode }}
      prefix: {{ .Release.Namespace }}
      {{- if (eq .Values.etcd.mode "external") }}
      servers:
      {{- range .Values.etcd.servers }}
      - {{ . }}
      {{- end }}
      caFile: "/controlplane_config/etcd_ca.crt"
      certFile: "/controlplane_config/etcd_cert.crt"
      keyFile: "/controlplane_config/etcd_cert.key"
      {{- end }}
  {{- if (and .Values.apiserver.ca .Values.apiserver.cakey) }}
  apiserver_ca.crt: {{ .Values.apiserver.ca | quote  }}
  apiserver_ca.key: {{ .Values.apiserver.cakey | quote  }}
  {{- end }}
  {{- if (eq .Values.etcd.mode "external") }}
  etcd_ca.crt: {{ .Values.etcd.ca | quote  }}
  etcd_cert.crt: {{ .Values.etcd.cert | quote  }}
  etcd_cert.key: {{ .Values.etcd.certkey | quote  }}
  {{- end }}
