apiVersion: v1
kind: Secret
metadata:
  name: controlplane-config
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  ocmconfig.yaml: |-
    apiserver:
      externalHostname: {{ .Values.apiserver.externalHostname }}
      port: 443
      {{- if .Values.apiserver.ca }}
      caFile: "/controlplane_config/apiserver_ca.crt"
      caKeyFile: "/controlplane_config/apiserver_ca.key"
      {{- end }}
    etcd:
      mode: {{ .Values.etcd.mode }}
      prefix: {{ .Release.Namespace }}
      {{- if (eq .Values.etcd.mode "external") }}
        {{- if (not .Values.etcd.servers) }}
          {{- fail "etcd.servers should be set together with etcd.mode" }}
        {{- end }}
      servers:
      {{- range .Values.etcd.servers }}
      - {{ . }}
      {{- end }}
      caFile: "/controlplane_config/etcd_ca.crt"
      certFile: "/controlplane_config/etcd_cert.crt"
      keyFile: "/controlplane_config/etcd_cert.key"
      {{- end }}

  {{- if .Values.apiserver.ca }}
  apiserver_ca.crt: {{ .Values.apiserver.ca | quote  }}
  apiserver_ca.key: {{ (required "apiserver.cakey should be set together with apiserver.ca" .Values.apiserver.cakey) | quote  }}
  {{- end }}
  {{- if (eq .Values.etcd.mode "external") }}
  etcd_ca.crt: {{ (required "etcd.ca should be set together with etcd.mode" .Values.etcd.ca) | quote }}
  etcd_cert.crt: {{ (required "etcd.cert should be set together with etcd.mode" .Values.etcd.cert) | quote }}
  etcd_cert.key: {{ (required "etcd.certkey should be set together with etcd.mode" .Values.etcd.certkey) | quote }}
  {{- end }}
