kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicluster-controlplane-agent
  labels:
    app: multicluster-controlplane-agent
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-controlplane-agent
  template:
    metadata:
      labels:
        app: multicluster-controlplane-agent
    spec:
      containers:
      - name: agent
        image: quay.io/open-cluster-management/multicluster-controlplane
        imagePullPolicy: IfNotPresent
        args:
          - "/multicluster-controlplane"
          - "agent"
          - "--cluster-name=cluster1"
          - "--bootstrap-kubeconfig=/spoke/bootstrap/kubeconfig"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - name: bootstrap-secret
          mountPath: "/spoke/bootstrap"
          readOnly: true
        - name: hub-kubeconfig
          mountPath: "/spoke/hub-kubeconfig"
      volumes:
      - name: bootstrap-secret
        secret:
          secretName: bootstrap-secret
      - name: hub-kubeconfig
        emptyDir:
          medium: Memory
