apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulsetservice.yaml
- statefulset.yaml

secretGenerator:
- name: trusted-ca
  files:
  - cert-etcd/ca.pem
generatorOptions:
  disableNameSuffixHash: true
