apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- statefulsetservice.yaml
- statefulset.yaml

secretGenerator:
- files:
  - cert-etcd/ca.pem
  name: trusted-ca
generatorOptions:
  disableNameSuffixHash: true
namespace: multicluster-controlplane-etcd
images:
- name: quay.io/coreos/etcd
  newName: quay.io/coreos/etcd
