# apply this role for controlplane when deploy to kind cluster
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: open-cluster-management:multicluster-controlplane-node
rules:
# list node in kind cluster to get servering IP
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
