kind: Deployment
apiVersion: apps/v1
metadata:
  name: multicluster-controlplane
  labels:
    app: multicluster-controlplane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multicluster-controlplane
  template:
    metadata:
      labels:
        app: multicluster-controlplane
    spec:
      containers:
      - name: controlplane
        image: quay.io/open-cluster-management/multicluster-controlplane
        imagePullPolicy: IfNotPresent
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        args:
          - "/multicluster-controlplane"
          - "server"
          - "--self-management"
          - "--controlplane-cert-dir=/.ocmconfig/cert"
          - "--config-file=/controlplane_config/ocmconfig.yaml"
          - "--feature-gates=DefaultClusterSet=true,OpenAPIV3=false"
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          runAsNonRoot: true
        volumeMounts:
        - name: controlplane-config
          mountPath: /controlplane_config
          readOnly: true
        - mountPath: /.ocmconfig
          name: ocmconfig 
      volumes:
      - name: controlplane-config
        secret:
          secretName: controlplane-config
      - name: ocmconfig 
        persistentVolumeClaim:
          claimName: multicluster-controlplane-pvc-volume
