apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multicluster-controlplane-node
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: open-cluster-management:multicluster-controlplane-node
subjects:
- kind: ServiceAccount
  name: multicluster-controlplane-sa
