# Copyright Contributors to the Open Cluster Management project
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: multicluster-controlplane-kubeconfig-creator
subjects:
- kind: ServiceAccount
  name: default 
  apiGroup: ""
roleRef:
  kind: Role        
  name: multicluster-controlplane-kubeconfig-creator
  apiGroup: rbac.authorization.k8s.io
